### PR TITLE
Signal to user what is the latest version of a package if they are about to install an older one

### PR DESCRIPTION
**Pull request by jvoigtlaender**
Before:

```
> elm-package install
Some new packages are needed. Here is the upgrade plan.

  Install:
    elm-lang/core 3.0.0
    jvoigtlaender/elm-memo 1.0.0
    maxsnew/lazy 1.1.0

Do you approve of this plan? (y/n)
```

After:

```
> elm-package install
Some new packages are needed. Here is the upgrade plan.

  Install:
    elm-lang/core 3.0.0
    jvoigtlaender/elm-memo 1.0.0 (latest package version is 2.0.3)
    maxsnew/lazy 1.1.0

Do you approve of this plan? (y/n)
```

(Both in a directory whose `elm-package.json` states `"jvoigtlaender/elm-memo": "1.0.0 <= v < 2.0.0"`.)

### CODE REVIEW

**Comment by jvoigtlaender** [comment]
@evancz, I did this in three commits to make it easier for you to review. Of course, I can squash them before merging.

(The Travis build failure is unrelated to this pull request.)

**Comment by jvoigtlaender** [comment]
I made this mergeable again. @evancz, this is the enhancement you encouraged me to have a go at implementing here: https://github.com/elm-lang/elm-package/issues/145#issuecomment-157429511.

**Comment by jvoigtlaender** [comment]
Rebased against current `master`.

**Comment by evancz** [comment]
I want to let people know about this, but I want to reveal the information in a more comprehensive way. It is good to know at install time that it is out of date, but it is better to know if it *ever* becomes out of date.

So this is something I want to do, and I do not think that keeping this open will help make it happen.

**Pull request closed without merging**
