### PR TITLE
Add --verbose arg and show how package dependency is being solved

### PR DESCRIPTION
**Pull request by ento**
### Motivation

Sometimes why elm-package is "unable to find a set of packages that will work with your constraints" is pretty nebulous. While not the most friendly interface, adding verbose logging will help diagnosing the problem by hands and eyes.

### Changes

* Added [hslogger](https://hackage.haskell.org/package/hslogger) for logging
* Added a `--verbose` argument
* Added logging to various places in Solver

This is my first Haskell code ever, so if something's not quite right, then it's most likely unintentional. Also I'm not familiar with the internals of Solver, so the way I phrased the logs may not be accurate.

### Output sample

For `elm-package.json` found in #176:

```
evancz/start-app = 2.0.2
elm-lang/core = 3.0.0
evancz/elm-svg = 2.0.1
mgold/Elm-Random-Sampling = 2.0.3
evancz/elm-html = 4.0.2
evancz/elm-html = 4.0.2 depends on evancz/virtual-dom: 2.0.0 <= v < 3.0.0
evancz/virtual-dom = 2.1.0, 2.0.0
evancz/elm-svg = 2.0.1 depends on evancz/virtual-dom: 1.2.0 <= v < 3.0.0
evancz/virtual-dom = 2.1.0, 2.0.0, 1.2.3, 1.2.2, 1.2.1, 1.2.0
evancz/start-app = 2.0.2 depends on evancz/elm-effects: 2.0.0 <= v < 3.0.0
evancz/elm-effects = 2.0.1, 2.0.0
mgold/Elm-Random-Sampling = 2.0.3 requires Elm version 0.15.0 <= v < 0.16.0 but we are on 0.16.0
evancz/virtual-dom = 2.0.0 requires Elm version 0.15.0 <= v < 0.16.0 but we are on 0.16.0
evancz/virtual-dom = 1.2.3 requires Elm version 0.15.0 <= v < 0.16.0 but we are on 0.16.0

Error: Unable to get elm-package.json for evancz/virtual-dom 1.2.2
Missing field "elm-version", acceptable versions of the Elm Platform (e.g. "0.16.0 <= v < 0.17.0").
    Check out an example elm-package.json file here:
    <https://raw.githubusercontent.com/evancz/elm-html/master/elm-package.json>
```

### CODE REVIEW

**Comment by eeue56** [comment]
+1, I like it. Only comment would be that adding a `verbose` flag should be different to displaying the messages - if a package can't be resolved, then it the conflict should always be printed out, regardless of verbosity.

**Comment by jvoigtlaender** [comment]
This is so cool! It would probably resolve the needs of people over at #119 as well. And maybe also #173. So @evancz, when merging this, the other issues could probably be closed.

**Comment by JustusAdam** [comment]
The UI seems a bit hard to read, but it's a start. :+1:

**Comment by rtfeldman** [comment]
+1 to @eeue56's comment - any time I get a failed dependency resolution, this is exactly what I want to know next, so might as well just tell me right away. :smile:

**Comment by ento** [comment]
Note: this PR breaks elm-make. [This patch unbreaks elm-make](https://github.com/ento/elm-make/tree/elm-package-logging-0.16-compat).

**Comment by EnoahNetzach** [comment]
Why isn't this already merged, after more than 5 months?
I just wanted to check elm out, I was so excited because it was "react + redux + haskell".
Now I'm just frustrated because I just installed it from npm and nothing works, and I have no idea how to solve it.

NOT the way to go...

**Comment by evancz** [comment]
The problem with this PR is that it does not *really* give hints that will be helpful for resolving the issue. Take the following `elm-package.json` as an example:

```json
{
    "version": "1.0.0",
    "summary": "helpful summary of your project, less than 80 characters",
    "repository": "https://github.com/user/project.git",
    "license": "BSD3",
    "source-directories": [
        "."
    ],
    "exposed-modules": [],
    "dependencies": {
        "elm-lang/core": "3.0.0 <= v < 4.0.0",
        "evancz/elm-html": "4.0.2 <= v < 5.0.0"
    },
    "elm-version": "0.17.0 <= v < 0.18.0"
}
```

Recording the entire search has two major problems:

  1. The search space is very very large. Picking a different version adds constraints, so things are quite tricky and the problem grows and changes as you solve it. Point is, when nothing solves, you just see tons of stuff that does not work.
  2. Having the "search history" makes no recommendation about how to fix anything.

So ultimately, this would mean that users get very long dumps of information that is not helpful in resolving the common issues.

I used this PR as motivation for "better hints" though. So I just got done taking a pass over error messages in `elm-package` that it produces the following message for the `elm-package.json` you see above:

screen shot 2016-06-01 at 12 26 13 am

Targeted suggestions that will help the user take the next steps. So I think the root motivation of this PR is coming through, but must take a different form to get to the heart of things.

**Pull request closed without merging**
