### PR TITLE
Use ExceptT instead of (deprecated) ErrorT

### PR DESCRIPTION
**Pull request by nathan**
This probably won't compile in GHC 7.10 without https://github.com/elm-lang/elm-package/pull/98.

See https://github.com/elm-lang/elm-repl/pull/56.

### CODE REVIEW

**Comment by evancz** [comment]
So `Control.Monad.Error` is deprecated, but `MonadError` still exists and it is in a module called `Control.Monad.Error.Class`? That seems really weird to me.

**Comment by evancz** [comment]
Is there a `MonadExcept`? Is it recommended that people start to move away from `MonadError`?

**Comment by nathan** [comment]
The difference between `ErrorT` and `ExceptT` is that `ErrorT` constrains the type of the error data with the `Error` class (e.g., compare [their `MonadError` instances](http://hackage.haskell.org/package/mtl-2.2.1/docs/src/Control-Monad-Error-Class.html#instance%20MonadError%20e%20%28ErrorT%20e%20m%29)). `MonadError` doesn't use `Error`, so it isn't deprecated and probably won't ever be.

**Comment by evancz** [comment]
Okay, looks good to me, thank you!

**Pull request merged**
