### PR TITLE
correct function reference

### PR DESCRIPTION
**Pull request by axelwathne**
I came across this while brewing elm. I don't know what I am doing, but the change seems reasonable looking at it.

### CODE REVIEW

**Comment by axelwathne** [comment]
The build failure looks unrelated to the change, "no rakefile found"

**Comment by zwilias** [comment]
It appears that `libraryVersion` isn't actually used anywhere. @evancz may prefer just removing it altogether.

**Comment by ilovezfs** [comment]
@evancz what is the status here?

**Comment by axelwathne** [comment]
Still "No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)", perhaps unsurprisingly

**Comment by evancz** [comment]
The code structure has changed a lot in preparation for 0.19, so I think it would have been long before this was initially opened that this code moved to a different repo.

I do not know what "brewing" means here, but there are many ways a Haskell build can fail. Since the development build now lives entirely in `elm-lang/elm-compiler`, I think it makes sense to close.

**Comment by axelwathne** [comment]
"brewing" here means building with homebrew (building and installing om Mac OS X) per this recipe: https://github.com/Homebrew/homebrew-core/blob/master/Formula/elm.rb -  which has since had the patch applied to allow building.

**Pull request closed without merging**
